# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Acategory.create(name:"19th Century Michigan Letters",status: 1)
Acategory.create(name:"20th Century",status: 1)
Acategory.create(name:"Michigan Advertising",status: 1)
Acategory.create(name:"American Home Missionary Society",status: 1)
Acategory.create(name:"Black History",status: 1)
Acategory.create(name:"Campbell Family Letters",status: 1)
Acategory.create(name:"MI Covers",status: 1)
Acategory.create(name:"Ernie's Ann Arbor Broken Ring",status: 1)
Acategory.create(name:"Ernie's Michigan Collection",status: 1)
Acategory.create(name:"MI Fancy Cancels",status: 1)
Acategory.create(name:"Letters to Foreign Destinations",status: 1)
Acategory.create(name:"MI Free Franks",status: 1)
Acategory.create(name:"MI Genealogy",status: 1)
Acategory.create(name:"German Language Letters",status: 1)
Acategory.create(name:"Ann Arbor Hampden Cancels",status: 1)
Acategory.create(name:"Machine Cancels",status: 1)
Acategory.create(name:"Manuscripts",status: 1)
Acategory.create(name:"Maps",status: 1)
Acategory.create(name:"Michigan Stampless Letters",status: 1)
Acategory.create(name:"Michigan Territorial",status: 1)
Acategory.create(name:"Northern Michigan",status: 1)
Acategory.create(name:"Ohio Toledo Strip Letters",status: 1)
Acategory.create(name:"MI Post Cards",status: 1)
Acategory.create(name:"Railroads",status: 1)
Acategory.create(name:"MI Waterways",status: 1)
Acategory.create(name:"Stamps",status: 1)
Acategory.create(name:"Wisconsin/Michigan Territory",status: 1)
Acategory.create(name:"Women's Correspondence",status: 1)
Acategory.create(name:"Thorp/Lybrook Family Letters",status: 1)
Acategory.create(name:"Love Letters",status: 1)
Acategory.create(name:"Leona & Frank Ohlhaussen Love Letters",status: 1)
Acategory.create(name:"Scott-10,11,25,26,26a",status: 1)
Acategory.create(name:"Michigan Territorial Exhibit",status: 1)
Acategory.create(name:"Michigan/Wisconsin Territory Exhibit",status: 1)
Acategory.create(name:"Detroit and Algonac Railway Post Office Exhibit",status: 1)
Acategory.create(name:"Michigan Railway Post Offices 1871-1915 Exhibit",status: 1)
Acategory.create(name:"Ransom Dunn",status: 1)
Acategory.create(name:"Letters Containing Correspondence",status: 1)
Acategory.create(name:"Privately Owned",status: 1)
Acategory.create(name:"Publicly Owned",status: 1)
Acategory.create(name:"Unusual Postage",status: 1)

Acounty.create(name:"Allegan",status: 1)
Acounty.create(name:"Arenacn",status: 1)
Acounty.create(name:"Berrien",status: 1)
Acounty.create(name:"Branch",status: 1)
Acounty.create(name:"Calhoun",status: 1)
Acounty.create(name:"Cass",status: 1)
Acounty.create(name:"Gennessee",status: 1)
Acounty.create(name:"Gladwin",status: 1)
Acounty.create(name:"Gratiot",status: 1)
Acounty.create(name:"Hillsdale",status: 1)
Acounty.create(name:"Ingham",status: 1)
Acounty.create(name:"Ionia",status: 1)
Acounty.create(name:"Isabella",status: 1)
Acounty.create(name:"Jackson",status: 1)
Acounty.create(name:"Kalamazoo",status: 1)
Acounty.create(name:"Kent",status: 1)
Acounty.create(name:"Lenawee",status: 1)
Acounty.create(name:"Lapeer",status: 1)
Acounty.create(name:"Livingston",status: 1)
Acounty.create(name:"Mackinac",status: 1)
Acounty.create(name:"Macomb",status: 1)
Acounty.create(name:"Midland",status: 1)
Acounty.create(name:"Monroe",status: 1)
Acounty.create(name:"Montcalm",status: 1)
Acounty.create(name:"Oakland",status: 1)
Acounty.create(name:"Oceana",status: 1)
Acounty.create(name:"Ottawa",status: 1)
Acounty.create(name:"Saginaw",status: 1)
Acounty.create(name:"Saint Clair",status: 1)
Acounty.create(name:"Saint Joseph",status: 1)
Acounty.create(name:"Sanilac",status: 1)
Acounty.create(name:"Shiwassee",status: 1)
Acounty.create(name:"VanBuren",status: 1)
Acounty.create(name:"Washtenaw",status: 1)
Acounty.create(name:"Wayne",status: 1)  


Acity.create(name:"Adrian",status: 1)
Acity.create(name:"AnnArbor",status: 1)
Acity.create(name:"BattleCreek",status: 1)
Acity.create(name:"Coldwater",status: 1)
Acity.create(name:"Detroit",status: 1)
Acity.create(name:"Dexter",status: 1)
Acity.create(name:"Flint",status: 1)
Acity.create(name:"Jackson",status: 1)
Acity.create(name:"Kalamazoo",status: 1)
Acity.create(name:"Monroe",status: 1)
Acity.create(name:"Niles",status: 1)
Acity.create(name:"Tecumseh",status: 1)
Acity.create(name:"Ypsilanti",status: 1)




